### ISSUE TITLE
Update react and draftjs to the latest versions

### ISSUE THREAD

**Issue by synbot** [synapsestudios/draftjs-editor#36]
## Goals

- [x] Sane defaults on height #34 
- [x] Bump `peerDependency` to add `|| ^16.0.0"` for both `react` and `react-dom`.  15.3 is a good default to begin with, as it is when pureComponents were introduced.
- [x] Passes in root styling for the root object of the editor to control height/width #34 
- [x] Allow passing of props directly into the Editor Component #32

There's a lot of issues opened that are easily solvable in userland by creating the ability to pass in the full complement of settings for draftJS, so improving prop passing should rectify many issues.

**Comment by bobeagan** [comment]
We still need to update this description
